
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import styles from '@/app/(auth)/layout.module.scss'

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.root}`}>
        <main className={`${styles.content_main}`}>
          {children}
        </main>
      </body>
    </html>
  );
}
