
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css"
import SideNavigation from "@/components/side_navigation/side_navigation";
import styles from '@/app/(home)/style.module.scss'

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type MenuItem =  {
  title: string
  path: string
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const menu_items: MenuItem[] = [{title: "Upload", path:'/'} , {title: 'Seating Records', path: 'seating'}]

  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.root}`}>
        <SideNavigation className={`${styles.navigation}`}/> 
        <main className={`${styles.content_main}`}>
          {children}
        </main>
      </body>
    </html>
  );
}
